language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - soul23.4ever@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
    secure: "OYpptnTZ4EgBAA3PzWXxIDuqXzlVgcZXIg794GjH++trzk249NFy1+AseakAX1ILgocAl7YyPpXzjDOKmwp3hao9h9A6jHhCI5neon2/XZ9F0DkV4K2rs/dnFuBYCu/8YV2ealYv5TkWmSUKZPSUgqupyrN5/8JJomkkzTLdwiiLUiNrcjAjoR7hP6Nx0Z6tKnXNVbHOWNJLh0+g103LEkLxpNLetDoMhsVyvNNfFDPntE9l6uebLSWPBbCzf08elrLKBSwb43Sr3BJJ1kv9iX17PeucFwjCA6LkM7AU35qRQrnwY6i4aWvvKHGuAz13yOpMGBcplAR8gXlnY5NTg9rV3JWlwiGipnwsGh4ei9D8/g8ig4S9h7V/LVioXDbFUjoBEmWNGS+8XAkJrhzD47bqKDDiqefUnYbU1Id7nPLHpumbJWOwquwoVSbrwiiQvYy8hN/v13Val+SnUNvLa3exY5qpxtaYJ+nvECYILrI4ntXYHxn0iWvJzKgZTDP4Oel4eujd718tgrOO6eIxjjTEiEiJcvTA0KND7RGFDbB6TZR7pDTaJ+zyC1bgHWwlxKSUphB5lYxsRgP6jBGBzDsRYXvy344eBVDZ/LdImRlELyN231Kc8bHcUAC4RKvsL8JQpWEdkeWVPyCcCTSIEmqFE/p7MxZqGQi8K0YkGBk="
  app: soul-store-backend
  on:
    repo: soulware23/platzi-store-backend