language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - soul23.4ever@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
    secure: "cgnMaAEmkqQUmzj70r6Fg9WWbrzbuZA2cEkBYETEIhoxaLVAapRuqKWGG7X0xlx5Xn+q2Za8FyfJkFedU8foIDparr77TPd8v2U57YRRLs4u6b7WIA1l5BGxwBw93+4YUoB+qTe/9Wapr5FdwvXaNdjzIUzHK5m/Hrgpmuy7IQ8jHl8KIx2CAxXhyVO4SJV8+Z/MASOHLuiCwGXe3zz7BE7GQ/Bl9Rg7w1NBtuJtz8VTVwoOk2A6g1CyMNltVrHO9itlCDXuSKICw1QDseO8+p6pHHQRFO5mC35IHKC3A72CV/GkCTapFNMG99vurdLwgMfb/1zPhc91G8sZ0ILLcfWqvPpJqCx3xsj+1hjkBEMfxKz20xhTfTEwN1Kpa3bqCAFn/o8fhCoIP042IEwF31i+ipqEu7jdHKhHSbBak/2GWUoV36oHafvVPjINQKXMZ+2NzD+Bs3H+Vj6DGyOmR8bAjQbRDkj5sE+Zgx8QajEkM/KOFR+VjWpdHSaW1JY4Oexh7fEOUlV1cXEjPmkLezqy9wgIW+UbiUonnjz70e+UNykDPazaGQTrn1YxYymOOj1FaLhYxo6qJbVf6uwYDXD2sAkwSINP/AySsTy9i+SQOD1VWx6O509nBNVYTNLweAtHRkdlnxjIe43jGkZltw4Hc9I+h+Gi1KyQVFI38Vg="
  app: soul-store-backend
  on:
    repo: soulware23/platzi-store-backend