language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - soul23.4ever@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 73283b1a-8694-4652-ae27-9f0ad912cbfc
  app: soul_store_backend
  on:
    repo: soulware23/platzi-store-backend